import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';

const root = new URL('../../web/', import.meta.url);

test('unified page exposes an accessible cited research workspace', async () => {
  const html = await readFile(new URL('index.html', root), 'utf8');
  assert.equal((html.match(/<main\b/g) || []).length, 1);
  assert.doesNotMatch(html, /class="ask-console"/);
  assert.match(html, /<h1 id="knowledge-heading">AI 行业报告知识库，<br>洞察皆有出处。<\/h1>/);
  assert.doesNotMatch(html, /问报告，也问证据。/);
  assert.doesNotMatch(html, /问报告，<br>/);
  assert.match(html, /<form[^>]+id="question-form"/);
  assert.match(html, /<label[^>]+for="question"/);
  for (const id of ['publisher-filter', 'date-filter', 'category-filter', 'priority-filter']) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(html, /id="answer"[^>]+aria-live="polite"/);
  assert.match(html, /id="article-results"/);
  assert.doesNotMatch(html, /id="source-drawer"/);
  assert.match(html, /id="article-dialog"/);
  assert.match(html, /id="api-status"/);
  assert.match(html, /id="knowledge-chat-button"[^>]+aria-label="问整个知识库"/);
  assert.match(html, /id="knowledge-chat-drawer"[^>]+role="dialog"[^>]+aria-modal="false"/);
  assert.match(html, /id="source-reader"/);
  assert.match(html, /id="source-reader-frame"/);
  const readerFrame = html.match(/<iframe\b[^>]*id="source-reader-frame"[^>]*>/)?.[0] || '';
  assert.match(readerFrame, /sandbox="allow-popups"/);
  assert.match(readerFrame, /referrerpolicy="no-referrer"/);
  assert.doesNotMatch(readerFrame, /allow-scripts|allow-same-origin/);
  assert.match(html, /id="source-reader-back"/);
  assert.match(html, /id="source-reader-pdf"[^>]+hidden/);
  assert.match(html, /<nav[^>]+aria-label="主导航"/);
  assert.match(html, /href="radars\/index\.html"[^>]*>AI机会雷达<\/a>/);
  assert.match(html, /data-link="chinese"/);
  assert.match(html, /data-link="original"/);
  assert.match(html, /data-link="official"/);
  assert.match(html, /data-link="pdf"[^>]+hidden/);
  assert.match(html, /id="sort-control"/);
  assert.match(html, /value="date"[^>]*>最新发布/);
  assert.match(html, /value="score"[^>]*>评分最高/);
  assert.match(html, /<script src="data\/topics\.js"><\/script>/);
  assert.match(html, /<script src="article-utils\.js"><\/script>/);
  assert.match(html, /<script src="chat-widget\.js"><\/script>/);
});

test('assets include responsive, accessible and safe rendering contracts', async () => {
  const [css, js, chat] = await Promise.all([readFile(new URL('styles.css', root), 'utf8'), readFile(new URL('app.js', root), 'utf8'), readFile(new URL('chat-widget.js', root), 'utf8')]);
  assert.match(css, /@media\s*\(max-width:\s*390px\)/);
  assert.match(css, /prefers-reduced-motion:\s*reduce/);
  assert.match(css, /:focus-visible/);
  assert.doesNotMatch(js, /\.innerHTML\s*=/);
  assert.doesNotMatch(js, /localStorage/);
  assert.doesNotMatch(js, /fetch\(['"]\/api\/ask/);
  assert.match(js, /KnowledgeChat\.init/);
  assert.doesNotMatch(chat, /\.innerHTML\s*=/);
  assert.match(chat, /localStorage/);
  assert.match(chat, /\/api\/health/);
  assert.doesNotMatch(css, /\.ask-workspace\s*\{/);
  assert.match(css, /\.knowledge-hero\s*\{[^}]*min-width:\s*0/);
  assert.match(css, /\.knowledge-hero-copy\s*\{[^}]*width:\s*min\(100%,\s*1180px\)/);
  assert.match(css, /\.knowledge-chat-drawer\s*\{[^}]*width:\s*min\(520px,\s*44vw\)/);
  assert.match(css, /\.source-reader\s*\{[^}]*right:\s*min\(520px,\s*44vw\)/);
  assert.match(css, /@media\s*\(max-width:\s*760px\)[\s\S]*\.knowledge-chat-drawer\s*\{[^}]*width:\s*100vw/);
  assert.match(css, /@media\s*\(max-width:\s*760px\)[\s\S]*\.source-reader\s*\{[^}]*inset:\s*0/);
  assert.match(js, /ArticleUtils\.sortArticles/);
  assert.match(js, /params\.set\('sort'/);
  assert.match(js, /window\.ARTICLE_TOPICS/);
  assert.doesNotMatch(js, /SOURCE SCORE/);
});
